### PR TITLE
improved help page

### PR DESCRIPTION
**Pull request by seankross**
## Description
[See title](https://youtu.be/xrg-RgF5F8o?si=9p7y_Ljw75mOkwbh)

### CODE REVIEW

**Review by sckott — COMMENTED** [review]
I think this content might be better presented as a bulleted list. e.g., like on the tidyverse.org help page https://www.tidyverse.org/help/#where-to-ask 

Should we mention that if it's a general programming question to go ask elsewhere and point them to where?

**Comment by seankross** [comment]
> Should we mention that if it's a general programming question to go ask elsewhere and point them to where?

Eh let's wait to see what kind of people find this page an act on it.

**Comment by seankross** [comment]
Thanks for the feedback @sckott, this is ready for further review.

**Comment by sckott** [comment]
icons for each bullet to visually signal? feel free to say nah i'm all set

Screenshot 2024-07-18 at 2 04 40 PM

**Review by sckott — APPROVED** [review]

**Pull request merged**
